name: Build documentation
          
on:
  push:
    # To trigger the workflow once you push to the `main` branch
    # Replace `main` with your branch’s name
    branches: ["main"]
  # Specify to run a workflow manually from the Actions tab on GitHub
  workflow_dispatch:

permissions:
  id-token: write
  pages: write

env:
  # Name of module and id separated by a slash
  INSTANCE: Writerside/sw
  # Replace XX with the ID of the instance in capital letters
  ARTIFACT: webHelpSW2-all.zip
  # Docker image version
  DOCKER_VERSION: 232.10275

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Writerside docs using Docker
        uses: JetBrains/writerside-github-action@v4
        with:
          instance: Writerside/sw
          artifact: webHelpSW2-all.zip
          docker-version: 233.14272

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: |
            artifacts/webHelpSW2-all.zip
          retention-days: 7

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # Requires build job results
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: docs

      - name: Unzip artifact
        run: unzip -O UTF-8 -qq webHelpSW2-all.zip -d dir

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: dir

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
